packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  "@tanstack/react-query": ^5.67.1
  "@trpc/client": ^11.0.0-rc.824
  "@trpc/tanstack-react-query": ^11.0.0-rc.824
  "@trpc/server": ^11.0.0-rc.824
  eslint: ^9.19.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.15
  typescript: ^5.8.2
  zod: ^3.23.8
  better-auth: ^1.2.4
  "@better-auth/expo": ^1.2.4
catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
ignoredBuiltDependencies:
  - core-js
